=== milospp/vaccine-is/schemas/interesovanje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/interesovanje"
    xmlns="http://www.ftn.uns.ac.rs/interesovanje" xmlns:zaj="http://www.ftn.uns.ac.rs/zajednicka">
    <xs:import namespace="http://www.ftn.uns.ac.rs/zajednicka" schemaLocation="zajednicka.xsd"/>
    <xs:element name="interesovanje">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element fixed="Држављанин Републике Сррбије" name="drzavljaninSrbije"/>
                    <xs:element fixed="Страни држављанин са боравком у РС" name="straniSaBoravkom"/>
                    <xs:element fixed="Страни држављанин без боравка у РС" name="straniBezBoravka"/>
                </xs:choice>
                <xs:element name="jmbg" type="zaj:STjmbg"/>
                <xs:element name="ime" type="zaj:STime"/>
                <xs:element name="prezime" type="zaj:STprezime"/>
                <xs:element name="email" type="zaj:STemail"/>
                <xs:element name="brojMobilnog" type="zaj:STmobilni"/>
                <xs:element name="brojFiksnog" type="zaj:STfiksni"/>
                <xs:element name="lokacijaPrimanja" type="zaj:STlokacija"/>
                <xs:choice>
                    <xs:element fixed="Pfizer-BioNTech" name="fajzer"/>
                    <xs:element fixed="Sputnik V (Gamaleya истраживачки центар)" name="sputnik"/>
                    <xs:element fixed="Sinopharm" name="sinopharm"/>
                    <xs:element fixed="AstraZeneca" name="astra"/>
                    <xs:element fixed="Moderna" name="moderna"/>
                    <xs:element fixed="Било која" name="biloKoja"/>
                </xs:choice>
                <xs:choice>
                    <xs:element fixed="Да" name="davalacKrvi"/>
                    <xs:element fixed="Не" name="nijeDavalacKrvi"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== milospp/vaccine-is/docs/interesovanje.xml
<?xml version="1.0" encoding="UTF-8"?>

<inter:interesovanje xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/interesovanje ../schemas/interesovanje.xsd"
    xmlns:inter = "http://www.ftn.uns.ac.rs/interesovanje">
    <inter:drzavljaninSrbije/>
    <inter:jmbg>0102998152031</inter:jmbg>
    <inter:ime>Иван</inter:ime>
    <inter:prezime>Мршуља</inter:prezime>
    <inter:email>mrki@gmail.com</inter:email>
    <inter:brojMobilnog>0631234156</inter:brojMobilnog>
    <inter:brojFiksnog>011123456</inter:brojFiksnog>
    <inter:lokacijaPrimanja>Нови Сад</inter:lokacijaPrimanja>
    <inter:sinopharm/>
    <inter:nijeDavalacKrvi/>
</inter:interesovanje>
