=== milospp/vaccine-is/schemas/obrazac-saglasnosti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/obrazac-saglasnosti"
    xmlns="http://www.ftn.uns.ac.rs/obrazac-saglasnosti"
    xmlns:zaj="http://www.ftn.uns.ac.rs/zajednicka">
    <xs:import namespace="http://www.ftn.uns.ac.rs/zajednicka" schemaLocation="zajednicka.xsd"/>
    <xs:element name="saglasnost">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="drzavljanstvo" type="zaj:STvrstaDrzavljanstva"/>
                <xs:element name="podaciPacijenta" type="pacijentSaglasnost"/>
                <xs:element name="evidencijaVakcinacije" type="evidencijaVakcinacije"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="pacijentSaglasnost">
        <xs:complexContent>
            <xs:extension base="zaj:STpersonalniPodaci">
                <xs:sequence>
                    <xs:element name="imeRoditelja"/>
                    <xs:element name="podaciMjesta">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="mjestoRodjenja"/>
                                <xs:element name="adresa">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="ulica"/>
                                            <xs:element name="broj"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="mjestoNaselje"/>
                                <xs:element name="opstinaGrad"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="kontaktPodaci">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="fiksniTelefon"/>
                                <xs:element name="mobilniTelefon"/>
                                <xs:element name="imejl"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="radniStatus" type="zaj:STradniStatus"/>
                    <xs:element name="zanimanjeZaposlenog" type="zaj:STzanimanje"/>
                    <xs:element name="socijalnaZastita">
                        <xs:complexType>
                            <xs:choice>
                                <xs:sequence>
                                    <xs:element name="korisnikSocijalnog" fixed="ДА"/>
                                    <xs:element name="nazivUstanove" type="zaj:STimeUstanove"/>
                                    <xs:element name="sjedisteUstanove" type="zaj:STlokacija"/>
                                </xs:sequence>
                                <xs:element name="nijeKorisnikSocijalnog" fixed="НЕ"/>
                            </xs:choice>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="izjavaSaglasnosti">
                        <xs:complexType>
                            <xs:choice>
                                <xs:sequence>
                                    <xs:element name="saglasan" fixed="САГЛАСАН САМ"/>
                                    <xs:element name="imeLijeka" type="zaj:STvrstaVakcine"/>
                                </xs:sequence>
                                <xs:element name="nesaglasan" fixed="НИСАМ САГЛАСАН"/>
                            </xs:choice>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="datumSaglasnosti" type="zaj:STdatum"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="evidencijaVakcinacije">
        <xs:sequence>
            <xs:element name="nazivUstanove" type="zaj:STimeUstanove"/>
            <xs:element name="vakcinacijskiPunkt"/>
            <xs:element name="podaciLjekara">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ime" type="zaj:STime"/>
                        <xs:element name="prezime" type="zaj:STprezime"/>
                        <xs:element name="faksimil" minOccurs="0"/>
                        <xs:element name="brojTelefona" type="zaj:STmobilni"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="podaciVakcinacija">
                <xs:complexType>
                    <xs:sequence>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="nazivVakcine" type="zaj:STvrstaVakcine"/>
                            <xs:element name="datumDavanjaVakcine" type="zaj:STdatum"/>
                            <xs:element name="nacinDavanjaVakcine" type="xs:string"/>
                            <xs:element name="ekstremitet" type="zaj:STekstremitet"/>
                            <xs:element name="serijaVakcine"/>
                            <xs:element name="proizvodjac" type="xs:string"/>
                            <xs:element name="nezeljenaReakcija" type="xs:string" minOccurs="0"/>
                            <xs:element name="potpisLjekara" minOccurs="0"></xs:element>
                        </xs:sequence>
                        <xs:element minOccurs="0" name="privremeneKontraindikacije">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="datumUtvrdjivanja" type="zaj:STdatum"/>
                                    <xs:element name="dijagnoza" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element minOccurs="0" name="odlukaKomisije" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== milospp/vaccine-is/docs/obrazac-saglasnosti.xml
<?xml version="1.0" encoding="UTF-8"?>

<obrazac:saglasnost xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/obrazac-saglasnosti ../schemas/obrazac-saglasnosti.xsd"
    xmlns:obrazac = "http://www.ftn.uns.ac.rs/obrazac-saglasnosti"
    xmlns:zaj="http://www.ftn.uns.ac.rs/zajednicka">
    
    <obrazac:drzavljanstvo>
        <zaj:stranoDrzavljanstvo>BIH</zaj:stranoDrzavljanstvo>
        <zaj:brojPasosa>008490806</zaj:brojPasosa>
    </obrazac:drzavljanstvo>
    
    <obrazac:podaciPacijenta>
        <zaj:ime>Милош</zaj:ime>
        <zaj:prezime>Панић</zaj:prezime>
        <zaj:pol>Женско</zaj:pol>
        <zaj:datumRodjenja>1999-06-25</zaj:datumRodjenja>
        <obrazac:imeRoditelja>Мајка</obrazac:imeRoditelja>
        <obrazac:podaciMjesta>
            <obrazac:mjestoRodjenja>Зрењанин</obrazac:mjestoRodjenja>
            <obrazac:adresa>
                <obrazac:ulica>Сарајевска</obrazac:ulica>
                <obrazac:broj>14</obrazac:broj>
            </obrazac:adresa>
            <obrazac:mjestoNaselje>Аеродромско насеље</obrazac:mjestoNaselje>
            <obrazac:opstinaGrad>Зрењанин</obrazac:opstinaGrad>
        </obrazac:podaciMjesta>
        <obrazac:kontaktPodaci>
            <obrazac:fiksniTelefon>023154684</obrazac:fiksniTelefon>
            <obrazac:mobilniTelefon>0658919849</obrazac:mobilniTelefon>
            <obrazac:imejl>cppanic@yahoo.com</obrazac:imejl>
        </obrazac:kontaktPodaci>
        <obrazac:radniStatus>незапослен</obrazac:radniStatus>
        <obrazac:zanimanjeZaposlenog>друго</obrazac:zanimanjeZaposlenog>
        <obrazac:socijalnaZastita>
            <obrazac:nijeKorisnikSocijalnog/>
        </obrazac:socijalnaZastita>
        <obrazac:izjavaSaglasnosti>
            <obrazac:saglasan/>
            <obrazac:imeLijeka>Pfizer-BioNTech</obrazac:imeLijeka>
        </obrazac:izjavaSaglasnosti>
        <obrazac:datumSaglasnosti>2021-11-30</obrazac:datumSaglasnosti>
    </obrazac:podaciPacijenta>
    
    
    <obrazac:evidencijaVakcinacije>
        <obrazac:nazivUstanove>Дом здравља Нови Сад</obrazac:nazivUstanove>
        <obrazac:vakcinacijskiPunkt>123</obrazac:vakcinacijskiPunkt>
        <obrazac:podaciLjekara>
            <obrazac:ime>Предраг</obrazac:ime>
            <obrazac:prezime>Кон</obrazac:prezime>
            <obrazac:brojTelefona>0631561558</obrazac:brojTelefona>
        </obrazac:podaciLjekara>
        <obrazac:podaciVakcinacija>
            <obrazac:nazivVakcine>Pfizer-BioNTech</obrazac:nazivVakcine>
            <obrazac:datumDavanjaVakcine>2021-11-01</obrazac:datumDavanjaVakcine>
            <obrazac:nacinDavanjaVakcine>ИМ</obrazac:nacinDavanjaVakcine>
            <obrazac:ekstremitet>Лијева рука</obrazac:ekstremitet>
            <obrazac:serijaVakcine>1591118</obrazac:serijaVakcine>
            <obrazac:proizvodjac>BioNTech</obrazac:proizvodjac>
            <obrazac:nezeljenaReakcija>Алергија на чоколаду</obrazac:nezeljenaReakcija>
            
            <obrazac:nazivVakcine>Pfizer-BioNTech</obrazac:nazivVakcine>
            <obrazac:datumDavanjaVakcine>2021-11-22</obrazac:datumDavanjaVakcine>
            <obrazac:nacinDavanjaVakcine>ИМ</obrazac:nacinDavanjaVakcine>
            <obrazac:ekstremitet>Лијева рука</obrazac:ekstremitet>
            <obrazac:serijaVakcine>711455</obrazac:serijaVakcine>
            <obrazac:proizvodjac>BioNTech</obrazac:proizvodjac>
            <obrazac:nezeljenaReakcija>Температура након једења чварака</obrazac:nezeljenaReakcija>
        </obrazac:podaciVakcinacija>
    </obrazac:evidencijaVakcinacije>
</obrazac:saglasnost>
