=== milospp/vaccine-is/vaccineis-backend/vaccineis-portal/data/izvjestaj-o-imunizaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" 
    targetNamespace="http://www.ftn.uns.ac.rs/izvjestaj" xmlns="http://www.ftn.uns.ac.rs/izvjestaj"
    xmlns:zaj="http://www.ftn.uns.ac.rs/zajednicka">
    <xs:import namespace="http://www.ftn.uns.ac.rs/zajednicka" schemaLocation="zajednicka.xsd"/>
    <xs:element name="izvjestaj">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="period">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pocetakPerioda" type="zaj:STdatum"/>
                            <xs:element name="krajPerioda" type="zaj:STdatum"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="brojInteresovanjaImunizacija" type="zaj:STpozitivanBroj"/>
                <xs:element name="sertifikatInfo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="brojZahtjeva" type="zaj:STpozitivanBroj"/>
                            <xs:element name="izdatoZahtjeva" type="zaj:STpozitivanBroj"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="brojDoza" type="zaj:STbrojDoze"/>
                <xs:element name="dozeVakcinaInfo">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="dozaInfo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="redniBrojDoze" type="zaj:STbrojDoze"/>
                                        <xs:element name="brojDatihDoza" type="zaj:STbrojDoze"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="raspodjelaDoza">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="tipVakcineInfo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nazivProizvodjaca" type="xs:string"/>
                                        <xs:element name="brojDoza" type="zaj:STbrojDoze"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datumIzdavanjaIzvjestaja" type="zaj:STdatum"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== milospp/vaccine-is/vaccineis-backend/src/main/resources/data/xml/izvjestaj-o-imunizaciji.xml
<?xml version="1.0" encoding="UTF-8"?>

<izv:izvjestaj
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/izvjestaj ../xsd/izvjestaj-o-imunizaciji.xsd"
    xmlns:izv = "http://www.ftn.uns.ac.rs/izvjestaj"
    xmlns:zaj="http://www.ftn.uns.ac.rs/zajednicka">
    
    <izv:period>
        <izv:pocetakPerioda>2021-08-01</izv:pocetakPerioda>
        <izv:krajPerioda>2021-09-01</izv:krajPerioda>
    </izv:period>
    
    <izv:brojInteresovanjaImunizacija>2758</izv:brojInteresovanjaImunizacija>
    
    <izv:sertifikatInfo>
        <izv:brojZahtjeva>453</izv:brojZahtjeva>
        <izv:izdatoZahtjeva>428</izv:izdatoZahtjeva>
    </izv:sertifikatInfo>
    
    <izv:brojDoza>3225</izv:brojDoza>
    
    <izv:dozeVakcinaInfo>
        <izv:dozaInfo>
            <izv:redniBrojDoze>1</izv:redniBrojDoze>
            <izv:brojDatihDoza>1789</izv:brojDatihDoza>
        </izv:dozaInfo>  
        
        <izv:dozaInfo>
            <izv:redniBrojDoze>2</izv:redniBrojDoze>
            <izv:brojDatihDoza>1276</izv:brojDatihDoza>
        </izv:dozaInfo> 
        
        <izv:dozaInfo>
            <izv:redniBrojDoze>3</izv:redniBrojDoze>
            <izv:brojDatihDoza>160</izv:brojDatihDoza>
        </izv:dozaInfo> 
    </izv:dozeVakcinaInfo>
    
    <izv:raspodjelaDoza>
        <izv:tipVakcineInfo>
            <izv:nazivProizvodjaca>Pfizer, BioNTech</izv:nazivProizvodjaca>
            <izv:brojDozaProizvodjac>1625</izv:brojDozaProizvodjac>
        </izv:tipVakcineInfo>
        
        <izv:tipVakcineInfo>
            <izv:nazivProizvodjaca>Sinopharm</izv:nazivProizvodjaca>
            <izv:brojDozaProizvodjac>1000</izv:brojDozaProizvodjac>
        </izv:tipVakcineInfo>
        
        <izv:tipVakcineInfo>
            <izv:nazivProizvodjaca>Sputnik V</izv:nazivProizvodjaca>
            <izv:brojDozaProizvodjac>356</izv:brojDozaProizvodjac>
        </izv:tipVakcineInfo>
        
        <izv:tipVakcineInfo>
            <izv:nazivProizvodjaca>AstraZeneca, Oxford</izv:nazivProizvodjaca>
            <izv:brojDozaProizvodjac>144</izv:brojDozaProizvodjac>
        </izv:tipVakcineInfo>

        <izv:tipVakcineInfo>
            <izv:nazivProizvodjaca>Moderna</izv:nazivProizvodjaca>
            <izv:brojDozaProizvodjac>100</izv:brojDozaProizvodjac>
        </izv:tipVakcineInfo>
    </izv:raspodjelaDoza>
    
    <izv:datumIzdavanjaIzvjestaja>2022-09-11</izv:datumIzdavanjaIzvjestaja>
</izv:izvjestaj>
